"""
GreyNOC CryptoScan — Markdown posture report + migration roadmap.

Turns a finding set into a CISO-readable report: an executive posture score,
the HNDL crown-jewel list, a severity-ranked findings table, and a prioritized
migration roadmap mapping each vulnerable primitive to its NIST PQC target.
"""

from __future__ import annotations

from datetime import datetime, timezone

from .classifier import Finding, summarize
from .primitives import QuantumRisk, Severity

_SEV_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
              Severity.LOW, Severity.INFO]


def _bar(score: int, width: int = 20) -> str:
    filled = round(score / 100 * width)
    return "#" * filled + "-" * (width - filled)


def render(findings: list[Finding], target: str) -> str:
    s = summarize(findings)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    lines.append(f"# GreyNOC Cryptographic Posture Report")
    lines.append("")
    lines.append(f"**Target:** `{target}`  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Scanner:** GreyNOC CryptoScan v0.1.0  ")
    lines.append(f"**Discipline:** authorized-testing-only · reproducible · no-fabrication")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive summary
    lines.append("## Executive summary")
    lines.append("")
    lines.append(f"**PQ-readiness score: {s['pq_readiness_score']}/100** "
                 f"`[{_bar(s['pq_readiness_score'])}]`")
    lines.append("")
    lines.append(f"- Cryptographic assets discovered: **{s['total_findings']}**")
    lines.append(f"- Quantum-vulnerable (Shor/Grover): **{s['quantum_vulnerable']}**")
    lines.append(f"- **Harvest-now-decrypt-later exposed: {s['hndl_exposed']}** "
                 f"(decryptable today, breakable later)")
    lines.append(f"- Already PQ-safe: **{s['pq_safe']}**")
    lines.append("")
    sev = s["by_severity"]
    lines.append(f"Severity spread — "
                 f"CRITICAL: {sev['CRITICAL']} · HIGH: {sev['HIGH']} · "
                 f"MEDIUM: {sev['MEDIUM']} · LOW: {sev['LOW']} · INFO: {sev['INFO']}")
    lines.append("")

    # HNDL crown jewels
    hndl = [f for f in findings if f.hndl_exposed()]
    if hndl:
        lines.append("## Priority 0 — Harvest-now-decrypt-later exposure")
        lines.append("")
        lines.append("These primitives establish or transport keys using a "
                     "Shor-breakable hard problem. Traffic captured today is "
                     "decryptable once a CRQC exists. Remediate first.")
        lines.append("")
        lines.append("| Algorithm | Where | Migrate to |")
        lines.append("|---|---|---|")
        for f in _dedupe(hndl):
            lines.append(f"| {f.fact.name} | `{f.locator}` | "
                         f"{'; '.join(f.fact.migrate_to) or '—'} |")
        lines.append("")

    # Full findings, severity-ranked
    lines.append("## Findings (severity-ranked)")
    lines.append("")
    lines.append("| Sev | Algorithm | Risk | Asset | Locator | Evidence |")
    lines.append("|---|---|---|---|---|---|")
    for f in sorted(_dedupe(findings),
                    key=lambda x: (-x.severity().rank, x.fact.name)):
        ev = f.evidence.replace("|", "\\|")[:48]
        lines.append(f"| {f.severity().value} | {f.fact.name} | "
                     f"{f.fact.risk.value} | {f.asset_type.value} | "
                     f"`{f.locator}` | `{ev}` |")
    lines.append("")

    # Migration roadmap
    lines.append("## Migration roadmap")
    lines.append("")
    roadmap = _roadmap(findings)
    if not roadmap:
        lines.append("No quantum-vulnerable primitives requiring migration. "
                     "Maintain crypto-agility and re-scan on each release.")
    else:
        for i, (algo, info) in enumerate(roadmap, 1):
            lines.append(f"### {i}. Replace {algo} ({info['count']} occurrence"
                         f"{'s' if info['count'] != 1 else ''})")
            lines.append("")
            lines.append(f"- **Risk:** {info['risk']} "
                         f"(max severity {info['severity']})")
            lines.append(f"- **Target:** {info['target']}")
            if info["note"]:
                lines.append(f"- **Rationale:** {info['note']}")
            lines.append(f"- **Locations:** "
                         + ", ".join(f"`{l}`" for l in info['locations'][:8])
                         + (" …" if len(info['locations']) > 8 else ""))
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("> Generated by GreyNOC CryptoScan. Findings are reproducible "
                 "from the scan inputs; each entry is tied to an observed "
                 "locator. Crypto-agility is the durable control — design "
                 "replacements behind an abstraction so the next migration is cheap.")
    return "\n".join(lines)


def _dedupe(findings: list[Finding]) -> list[Finding]:
    seen: set[str] = set()
    out = []
    for f in findings:
        if f.fingerprint not in seen:
            seen.add(f.fingerprint)
            out.append(f)
    return out


def _roadmap(findings: list[Finding]):
    """Group vulnerable findings by algorithm, build a prioritized plan."""
    groups: dict[str, dict] = {}
    for f in findings:
        if f.fact.risk in (QuantumRisk.SAFE,):
            continue
        g = groups.setdefault(f.fact.name, {
            "count": 0, "risk": f.fact.risk.value,
            "severity": Severity.INFO, "target": "; ".join(f.fact.migrate_to) or "—",
            "note": f.fact.note, "locations": [],
            "_rank": f.severity().rank,
        })
        g["count"] += 1
        g["locations"].append(f.locator)
        if f.severity().rank >= g["_rank"]:
            g["_rank"] = f.severity().rank
            g["severity"] = f.severity().value
    # Sort by worst severity, then by count.
    ordered = sorted(groups.items(),
                     key=lambda kv: (-kv[1]["_rank"], -kv[1]["count"]))
    return ordered
